### ISSUE TITLE
defaults should probably be renamed

### ISSUE THREAD

**Issue by mpdehaan** [ccollicutt/pound#1]
Just a heads up:

https://github.com/curtisgithub/pound/blob/master/defaults/main.yml

These should probably be prefixed with "pound_" as they could clash with other roles.

Role "vars/" directories have namespace collision detection but defaults do not (since they are basically inventory scope).

If you choose to update these, you can just press the "re-import" button in Galaxy to update the readme.

**Comment by ccollicutt** [comment]
Thanks, didn't know that was an issue, fixed. :)
